thechangelog/transcripts

gotime/go-time-48.md
ALEXANDER NEUMANN didn't talk about the legal stuff, Erik did. ALEXANDER NEUMANN interrupted with "yeah" and such.
I clarified who was speaking.
=> Clarity of who said what

jsparty/js-party-19.md
🎧   thanks for doing transcripts! this PR updates all the unintelligibles in jsparty 19. cheers!
=> Update unintelligibles on jsparty 19

rfc/request-for-commits-5.md
fill in some [unintelligible]s
plus a couple of corrections
=> improve transcript for RFC Ep5

gotime/go-time-58.md
There was an extra 'h' there. :)
=> Fix typo in shurcooL username.

spotlight/spotlight-4.md
Updated unintelligibles and changed "the" to 'then" ("because the people will wonder ...).
=> Update unintelligibles on spotlight-4

jsparty/js-party-10.md
Fixed timestamps:
* https://changelog.com/jsparty/10#t=00:02:00.18
* https://changelog.com/jsparty/10#t=00:02:52.19
=> Fill in some unintelligibles

gotime/go-time-59.md
=> sed -i 's,Stapleberg,Stapelberg,g' gotime/go-time-59.md

podcast/the-changelog-264.md
As uncanny as [Sophia](http://www.hansonrobotics.com/robot/sophia/)
=> Uncanny valley in the-changelog-264

jsparty/js-party-13.md
Fix some unintelligibles.
(Came here from The Changelog 317 btw. Great podcast! 😎)
=> Fix some unintelligibles on js-party-13

podcast/the-changelog-315.md
Fixed a bunch of 'unintelligibles'.
Again, could not really catch what was said at **00:27:54.15** due to the overlapping chatter, but managed to catch the tail-end of that sentence though.
=> Fixed a bunch of 'unintelligibles' on The Changelog 315

podcast/the-changelog-242.md
The idiom goes "struck a chord" not "struck a cord"
=> Misspelling in idiom

jsparty/js-party-10.md
This should wipe the unintelligible sections out of `js-party-10.md`, and clean up a few typos along the way.
=> Cleaned up unintelligible segments in `js-party-10`

practicalai/practical-ai-4.md
Fixing all the unintelligibles in practical ai episode 4
=> Fixing all the unintelligibles in practical ai episode 4

practicalai/practical-ai-7.md
Fixing all the unintelligibles in practical ai episode 7
=> Fixing all the unintelligibles in practical ai episode 7

jsparty/js-party-14.md
Replace 'unintelligible' markers with what was said. Update occasional timestamp for better accuracy.
=> Fixed unintelligibles in JSParty episode 14

podcast/the-changelog-315.md
Wrap the interposed sentence "I think" in commas as opposed to parantheses.
=> interposed sentence

jsparty/js-party-15.md
Fixed unintelligible but couldn't understand what is being said @ 54:42.21 and 56:29.10.
=> js-party-15.md fix unintelligible

jsparty/js-party-9.md
This PR replaces the 'unintelligible' sections of the transcript with the correct word / phrase.
=> Fix unintelligible sections in JS Party Episode 9

podcast/the-changelog-301.md
Fix unintelligible for the-changelog-301
=> Fix unintelligible for the-changelog-301

podcast/the-changelog-315.md
Fix unintelligible for the-changelog-315
=> Fix unintelligible for the-changelog-315

jsparty/js-party-17.md
Updated some of the unintelligible portions.
https://changelog.com/jsparty/17
=> Updated unintelligible on js-party-17

jsparty/js-party-25.md
Fix unintelligible to intelligible
=> Fix unintelligible

podcast/the-changelog-261.md
Fixed handful of unintelligible clips.
=> Updated unintelligible clips in changelog episode 261.

jsparty/js-party-meet-rachel-white.md
Replace remaining unintelligible flags with what was said
=> fix unintelligibles in js-party-meet-rachel-white

backstage/backstage-1.md
Replacing almost every unintelligible with what was said.
=> Replacing unintelligible with correct words in backstage-1

backstage/backstage-1.md
wrote some extra stuff to be more descriptive towards the story
=> wrote some more stuff on lines 1, 7, 11

podcast/the-changelog-253.md
Only 3 remaining which I wasn't able to get
=> [Changelog 253] Cleaning up 6 unintelligibles and spelling

podcast/the-changelog-258.md
=> [Changelog 258] Fixed most unintelligables

podcast/the-changelog-238.md
I couldn't make out one of the words at section `\[unintelligible 01:04:05.24\]` but it sounded like "dis..." so that's what I put in.
=> Fixed 'unintelligibles' for transcript #238

founderstalk/founders-talk-54.md
=> Fixed unintelligble for Founders Talk #54

gotime/go-time-75.md
=> Fixed unintelligible for Go Time #75

jsparty/js-party-46.md
Fixed unintelligible for JS Party #46
=> Fixed unintelligible for JS Party #46

rfc/request-for-commits-2.md
Fixes only unintelligible in transcript for Episode #2 of Request for Commits.
=> Fixed unintelligible for Request for Commits #2

gotime/go-time-65.md
Fixes the only unintelligible in Go Time episode 65.
=> Fixes unintelligible in go-time-65

jsparty/js-party-43.md
Fixes the last unintelligible in JS Party episode 43.
=> Fixes last unintelligible in js-party-43

rfc/request-for-commits-6.md
Fixes the only unintelligible in Request for Commits episode 6.
=> Fixes unintelligible in request-for-commits-6

podcast/the-changelog-219.md
Fixed unintelligible for Changelog #219
=> Fixed unintelligible for Changelog #219

gotime/go-time-53.md
Fixed unintelligible for Go Time #53
=> Fixed unintelligible for Go Time #53

jsparty/js-party-37.md
Fixed unintelligible for JS Party #37
=> Fixed unintelligible for JS Party #37

spotlight/spotlight-8.md
add this list of servers to \[unintelligible 00:10:08.15\] but by publishing it
to
add this list of servers to their etc hosts file or something... but by publishing it
=> Update \[unintelligible 00:10:08.15\] with text

podcast/the-changelog-244.md
Couldn't get the last one, but I think all the others are good! 
issue https://github.com/thechangelog/transcripts/issues/23
=> Fix some unintelligible tags in episode 244 transcript

gotime/go-time-11.md
Fixed unintelligible for Go Time #11
=> Fixed unintelligible for Go Time #11

gotime/go-time-43.md
Fixed unintelligible for Go Time #43
=> Fixed unintelligible for Go Time #43

jsparty/js-party-5.md
Fix line: **Juan Pablo Buritica:** I need five minutes \[unintelligible 00:52:56.09\]
To: **Juan Pablo Buritica:** I need five minutes. I am a procrastinator.
=> Fix 1 unintelligible JS Part Episode 5

jsparty/js-party-17.md
Podcast link: https://changelog.com/jsparty/17
Fix line 124: regardless of how much the content  \[unintelligible 00:17:01.22\]
to: regardless of how much the content costs to make 
Fix line 296: I'm \[unintelligible 00:42:07.04\]
To:  I'm continually surprised
=> Fix 2 unintelligibles in JS Part Episode 17

jsparty/js-party-bonus-suz-at-oscon.md
Fix all remaining unintelligibles
=> fix unintelligibles in js-party-bonus-suz-at-oscon

jsparty/js-party-22.md
Fix all remaining unintelligibles
=> fix unintelligibles in js-party-22

jsparty/js-party-24.md
Fix remaining unintelligibles.
=> fix unintelligibles in js-party-24

podcast/the-changelog-320.md
Changed one unintelligible and fixed other typos/wrong words.
=> Fixing typos

podcast/the-changelog-242.md
=> [Changelog 242] Fixed most of the unintelligables

podcast/the-changelog-244.md
Remove the last unintelligible from this episode
=> [Changelog 244] Fixed last unintelligible.

podcast/the-changelog-256.md
=> Fix unintelligible entries in episode 256.

podcast/the-changelog-237.md
=> Fix unintelligible entries in episode 237.

podcast/the-changelog-259.md
=> Fix some unintelligibles in thechangelog episode 259

podcast/the-changelog-315.md
https://en.wikipedia.org/wiki/Fediverse
=> Suggested spelling of Fediverse not FedeVerse

podcast/the-changelog-247.md
Fixes guest name in [podcast number 247](https://changelog.com/podcast/247), issue #23
=> Fix guest name

brainscience/brain-science-3.md
\[unintelligible 00:38:02.03\]
\[unintelligible 00:24:16.10\]
=> fix-unintelligible

gotime/go-time-100.md
Fixed unintelligible at given time
=> fix [unintelligible 00:06:55.10\]

gotime/go-time-31.md
Fixed some typos and unintelligibles in Go Time episode 31.
=> Fix typos and update unintelligibles on go-time-31.md

gotime/go-time-32.md
Fixed some typos and unintelligibles in Go Time episode 32.
=> Fix typos and update unintelligibles on go-time-32.md

jsparty/js-party-62.md
=> Fixed unintelligibles in "From voice devices to mobile, you just can't escape JS"

podcast/the-changelog-362.md
There were still 3 unintelligibles that I couldn't decipher, but this cleans up the other 4.
=> Cleaned up some unintelligibles in episode 362

podcast/the-changelog-359.md
I've fixed an unintelligible from  the-changelog-359.md of \[unintelligible 00:17:06.15\] .
=> Fixing unintelligble from the-changelog-359.md

jsparty/js-party-84.md
=> fix: unintelligible fragment, jsparty 84

podcast/the-changelog-355.md
=> fix: unintelligible fragments changelog 355

podcast/the-changelog-228.md, podcast/the-changelog-291.md
Supplement those parts that i understand
=> Podcast 228 improvement

jsparty/js-party-82.md
A few that were hard to make out have been left in
=> Fix most unintelligibles in JS Party 82

backstage/backstage-6.md
Some cross talk ones are truncated if they are unclear
=> Fix unintelligibles in Backstage 6

jsparty/js-party-92.md
I'm not sure how to spell Erin/Aaron's name, but I took a stab at it!
=> Fixed most unintelligibles in js-party-92

podcast/the-changelog-364.md
=> [Changelog 364] Fixed most unintelligables

founderstalk/founders-talk-60.md
=> Fixed an unintelligible term

jsparty/js-party-97.md
Replaced some unintelligibles in JS Party 97.
Please let me know if I need to change anything. Thanks.
=> Fix unintelligibles in js-party-97.md

gotime/go-time-4.md
Fix unintelligibles in go time 4.
Just one left.
=> Fix 5 unintelligible in gotime 4

gotime/go-time-25.md
Fix up go time 25, now unintelligible free.
=> Fix 14 unintelligible in go time 25

gotime/go-time-100.md
Seems like there is one unintelligible left in Go Time 100. Let me know if there is anything I need to change. Cheers.
=> Cleaned up remaining unintelligible in go-time-100

podcast/the-changelog-243.md
Fixed most unintelligibles in the-changelog-243.md
=> Fixed several unintelligibles in changelog-243

podcast/the-changelog-360.md
=> [Changelog 360] Fixed most unintelligables

jsparty/js-party-98.md
Listened to the podcast and updated unintelligible parts that I could other than one near the beginning of someone's user name in the chat that I couldn't understand (\[unintelligible 00:04:39.23\]).
=> Updated JS Party 98 Transcript

practicalai/practical-ai-33.md
=> Fixed unintelligible keyword.

gotime/go-time-101.md
- Fill some unintelligibles
- Remove some extraneous text
- Link to referenced talks and articles
=> Improve go-time-101 transcript

podcast/the-changelog-341.md
Got as many as I could figure out
=> fix some unintelligibles

podcast/the-changelog-296.md
Pedantic fix – loved listening to the episode and thanks for the mention!
=> s/My Society/mySociety

podcast/the-changelog-354.md
=> fix small omission in transcript

gotime/go-time-121.md
I did my best to hear those (especially 00:43:26.22), but please double-check it, just in case.
=> Go Time #121 - fix unintelligibles

gotime/go-time-2.md
Fixed the Unintelligible to transpiles.
=> Fix : transpiles

gotime/go-time-5.md
Fixed some typos like : dox, an.
Added standard library too.
=> fix: typos

gotime/go-time-5.md
We can try is said by Erik St. Martin.
=> We can try is said by Erik

gotime/go-time-8.md
Changes Include:
- Fixing the name of Asim Aslam in different places
- Adding cat with grep and ls instead of unintelligible
- Fixed Diskfg to discfg
- fixed VLCs to VLC
=> Fixes on GotimeFM 08

jsparty/js-party-142.md
I assume this was a transcription typo. Love the podcast :)
=> Horse stans Rust

jsparty/js-party-142.md
=> JS Party 142 with Horse JS links

backstage/backstage-8.md
=> updated backstage-8.md

backstage/backstage-12.md
=> updated backstage-12.md

jsparty/js-party-144.md
Was able to fix four of the five unintelligibles. Could not get the one at 01:00:43.28 due to laughter and crosstalk.
=> Fix unintelligibles in js-party-144

jsparty/js-party-112.md
Filled in unintelligible moments and fixed some other areas.
=> JS-Party-112 - transcript edits

podcast/the-changelog-411.md
=> [Changelog 411] Fixed most unintelligables

podcast/the-changelog-414.md
=> Podcast 414 Updates

podcast/the-changelog-410.md
Found and fixed all the unintelligables!
=> [Changelog 410] Fixed unintelligables

gotime/go-time-152.md
Unintelligibles for go-time 152
=> Fix unintelligibles in go-time 152

podcast/the-changelog-399.md
Cleaned up some of the unintelligibles. Changed "cork" to "quark."
=> Fixed unintelligibles in 399

podcast/the-changelog-396.md
Cleaned up a few unintelligibles in 396
=> Fixed unintelligibles in 396

podcast/the-changelog-393.md
Cleaned up a few unintelligibles in 393
=> Fixed unintelligibles in 393

podcast/the-changelog-417.md
Small typo. I was sure I saw another one in this transcript, but can't find it anymore (it was a mixup of letters).
It was really interesting to read!
=> the-changelog-417.md: kron -> cron

gotime/go-time-12.md, gotime/go-time-13.md, gotime/go-time-14.md
Fixed a number of unintelligible across Go Time Episode 12, 13, and 14. I provided links where I believe it made sense to. Unfortunately, I couldn't get all the unintelligible as there were some names that I couldn't track down, sorry! Hope this helps!
=> Fix unintelligible in GoTime FM

podcast/the-changelog-416.md
=> Podcast 416

gotime/go-time-152.md, jsparty/js-party-146.md
Small updates to Go Time 152 && JS Party 146
=> Go Time & JS Party Updates

jsparty/js-party-149.md
Small fixes and full-doc sub of C\# => C#
=> Js Party 149

gotime/go-time-154.md, podcast/the-changelog-419.md
Minor updates to Changelog 419 & Go Time 154
=> Small Updates on Changelog & Go Time

gotime/go-time-157.md, jsparty/js-party-153.md, podcast/the-changelog-421.md
minor fixes, tense changes, and unintelligible corrections on Go Time 157, JS Party 153, and Changelog 421
=> Various Fixes

podcast/the-changelog-424.md
As a participant in the conversation (and as the speaker in most cases),
I'm fairly confident in these interpretations.
=> Interpret unintelligible utterances

podcast/the-changelog-450.md
Hey, thanks for the transcript. I love it.
I've noticed a small typo and that the speaker was inverted in some exchanges ( it felt weird that Gary has 40-50 plugins and is said to have a barebone config right after.
=> Fix typo and speaker

gotime/go-time-199.md
=> Fix unintelligible in go-time-199

gotime/go-time-200.md
Got most 5 left.
Spotted a few minor errors too.
=> Fix unintelligible in go-time-200

podcast/the-changelog-466.md
=> Updated transcript for episode 466

gotime/go-time-59.md, scripts/format.js
=> Fix "Open Source.com"

shipit/ship-it-62.md
Also fix attribution for a section and tense of `fix`.
related: https://www.heroku.com/dynos
=> update ship-it-62 typo: dino -> dyno

jsparty/js-party-86.md
Is it mowing or moving? I am not sure. 
Thanks for the podcast & transcript. Loved it.
=> Verbiage change - mowing to moving

afk/away-from-keyboard-10.md
Fixed a typo to keep the MinneDemo branding.
=> Changed MiniDemo to MinneDemo, per context and guest

shipit/ship-it-56.md
I fixed all of the _unintelligible_s I could and added a couple of
links where I could.
=> Fix unintelligibles + add some links to shipit-56

shipit/ship-it-11.md
Got most unintelligible, just 2 left in this one.
=> Fix unintelligibles in ship-it-11

podcast/the-changelog-489.md
Fixed all unintelligibles in the-changelog-489.md
=> Fixed all unintelligibles in the-changelog-489.md

shipit/ship-it-68.md
fixed one unitelligible in ship-it-68
=> fixed one unitelligible in ship-it-68

podcast/the-changelog-515.md
fixed one unintelligible and added a link in the-changelog-515.md
=> fixed one unintelligible and added a link in the-changelog-515.md

shipit/ship-it-83.md
fixed some unintelligibles in ship-it-83
=> fixed some unintelligibles in ship-it-83

shipit/ship-it-62.md
fixed last unintelligibles and added links in ship-it-62.md
=> fixed last unintelligibles and added links in ship-it-62.md

podcast/the-changelog-news-2023-04-03.md
I thought I would just fix a few typos, but it turned into a thing. ¯\\\_(ツ)\_/¯
Were you trolling Daniel by including that soundbite? I guess I could've used Whisper to do the transcription and asked ChatGPT to summarize the salient points, but I did it the old-fashioned way instead. Here's the original, if you were looking for 100% accuracy:
> The model has no clue what it's saying, and nor does it have any, sort of, like, morality or, uh, like, it has no clue what it's saying, right? It's just producing coherent output, the same whether it's a text-to-image model, or it's a language model, like, there's no basis in, like, knowing what it's saying. It's auto-completing text, right? Like, at the end of the day, yes, like, that's a vast over-simplification, and you can not like that, but, …
=> Fix some typos, transcribe Practical AI soundbite (Changelog News 2023-04-03.md)

friends/changelog--friends-13.md
Note: I'm not 100% sure about the first sentence, in line 371, but I'm fairly confident that's at least pretty close to what he said.
=> Fix some unintelligible bits in transcript for Changelog & Friends n.13

podcast/the-changelog-556.md
Fixed remaining unintelligibles in changelog-556
=> Fixed remaining unintelligibles in changelog-556

podcast/the-changelog-405.md
Resolved the unintelligible text from the transcript from Changelog Interviews #405.
=> Resolve the unintelligible text in the changelog-405 transcript

friends/changelog--friends-16.md
Fixed all the unintelligible text part from the transcript: changelog--friends-16.md.
=> Update the transcript for changelog--friends-16.md

spotlight/spotlight-10.md, spotlight/spotlight-12.md, spotlight/spotlight-14.md, spotlight/spotlight-15.md, spotlight/spotlight-6.md, spotlight/spotlight-7.md, spotlight/spotlight-9.md
Worked on 6, 7, 9, 10, 12, 14, and 15.
=> Update - spotlight unintelligible

podcast/the-changelog-561.md
=> Fix 561 Unintelligibles

podcast/the-changelog-608.md
Fixes all unintelligibles in 608
=> Fixes Changelog 608 Unintelligibles

podcast/the-changelog-609.md
Fixes all Unintelligibles in 609
=> Fixes Changelog 609 Unintelligibles

podcast/the-changelog-610.md
Fixes all uninteligibles in 610
=> Fixes Changelog 610 Unintelligibles

podcast/the-changelog-612.md
Fixes most of them, only 2 left that I wasn't 100% on.
=> Fixes Changelog 612 Unintelligibles

podcast/the-changelog-643.md
Just a few name spelling corrections for you!
=> Correct names mentioned in 643
